import pandas as pd

def read_attendance(file):
    """Read an attendance.xslx and extract data.

    Parameters
    ----------
    file : str
        Path to the attendance.xlsx file. The file should have the standard form as generated by Co-Tutor at Loughborough University.   

    Returns
    -------

    attendance_df : pandas.DataFrame
        DataFrame containing the attendance data for each student.
    """
    attendance_df = pd.read_excel(file)

    # Keep student ID, overall attendance and individual lecture attendance columns
    attendance_df = attendance_df.iloc[:, [2, 4] + list(range(5, attendance_df.shape[1]))]

    # Change the names for the first two columns
    attendance_df = attendance_df.rename(
        columns={
            attendance_df.columns[0]: "Regno",
            attendance_df.columns[1]: "Attendance"
        }
    )
    # Chnage lecture attendance from 'GPS' to 1 and 0 otherwise
    attendance_df.iloc[:, 2:] = (
        attendance_df.iloc[:, 2:]
        .eq("GPS")
        .astype(int)
    )

    return attendance_df