import pandas as pd

def read_attendance(file):
    """Read an attendance.xslx and extract data.

    Parameters
    ----------
    file : str
        Path to the attendance.xlsx file. The file should have the standard form as generated by Co-Tutor at Loughborough University.   

    Returns
    -------

    attendance_df : pandas.DataFrame
        DataFrame containing the attendance data for each student.
    """
    attendance_df = pd.read_excel(file)

    # Only keep columns with student ID and overall attendance in attendance_df and rename columns
    attendance_df = attendance_df.iloc[:,[2,4]]
    attendance_df.columns = ["Regno", "Attendance"]

    return attendance_df